### ISSUE TITLE
Directory layer

### ISSUE THREAD

**Issue by josephg** [josephg/node-foundationdb#12]
Port the directory layer from the old codebase

**Comment by ashleybrener** [comment]
@josephg what is required here, is it purely porting the javascript layer to typescript?

And are we porting from the old lib, or 1 of the other language bindings?

**Comment by josephg** [comment]
Yeah we need to write a functional typescript version of the directory code on the new promise-based APIs. So either port the old JS or port the code from another binding. It’s all pretty consistent anyway, so I don’t think it matters much.

The other part is to add bindingtester support for the directory layer to test it; which practically speaking means adding a handful of new binding tester operations based on the spec (sorry on my phone - no links while I’m out)

**Comment by ex3ndr** [comment]
Are you open to pull requests without such tests? Missing directory layer is a deal breaker for me.

**Comment by josephg** [comment]
The main work here is done. I'm updating the binding tester now to thrash the code and then I'll release the directory layer, along with a bunch of other changes as 1.0.

**Comment by josephg** [comment]
Binding tester on the directory layer is passing. (Though I'm going to leave it on overnight to be sure.)

If it all checks out I'm going to cut 1.0 tomorrow with the directory layer 🎉

**Comment by josephg** [comment]
📦 foundationdb@1.0.0 with directory layer support!
