### ISSUE TITLE
Support new 6.1 database init flow

### ISSUE THREAD

**Issue by ryanworl** [josephg/node-foundationdb#23]
https://forums.foundationdb.org/t/upcoming-c-api-changes-planned-for-version-6-1/1058

Looks to be literally just deleting the ceremony for creating the database and replacing with a one-liner

**Comment by josephg** [comment]
So here's a question: When do I implement this? Doing so will force everyone using the library to update to fdb 6.1+.

**Comment by ryanworl** [comment]
The old symbols in the C library aren’t going away. You could check what version you’re targeting at runtime.

**Comment by josephg** [comment]
Ah whew. I guess that makes sense. It might make sense to just pave over this part of the API regardless of which API version the user selects.

**Comment by josephg** [comment]
... Well, waiting a year makes this easier :D. I'm compiling against version 620 of the API and using the new functions. I've stubbed out the API in javascript so people don't have to update their code, though it spits out warning messages if they try.
