### ISSUE TITLE
Versionstamps don't get filled in tuples with scoped transactions

### ISSUE THREAD

**Issue by aikoven** [josephg/node-foundationdb#24]
```ts
const subspace = db.at('some-prefix').withValueEncoding(fdb.encoders.tuple);

const value = await db.doTransaction(async tn => {
  const value = [fdb.tuple.unboundVersionstamp()];
  tn.scopedTo(subspace).setVersionstampedValue('some-key', value);
  return value;
});
```

If I `console.log` the value returned from the transaction, I get `[{ type: 'unbound versionstamp', code: undefined }]`. It seems that the `value` tuple gets to `valsToBake` of the scoped transaction, and does not propagate to the root transaction, for which the `_exec` method is called.

**Comment by josephg** [comment]
Good catch... I've added your test case and fixed it by refactoring the `valsToBake` stuff out.

**Comment by josephg** [comment]
📦 0.9.0 !

**Comment by aikoven** [comment]
Wow, that was fast! 👏

Thanks for this amazing library!

**Comment by josephg** [comment]
:) thanks for a great big report!
