### ISSUE TITLE
Unhandled promise rejection when restarting one of FDB nodes

### ISSUE THREAD

**Issue by aikoven** [josephg/node-foundationdb#37]
My app is doing serial read-modify-write transactions, and when I restart one of FDB nodes, I get unhandled promise rejections:

```
  FDBError {
    code: 2020,
    message: "Transaction does not have a valid commit version"
  }
```
I'm not sure where these are coming from, because there's no stack trace. Though I'm pretty sure they don't come from my code, which looks like this:

```ts
async function main() {
  while (true) {
    await doTransaction(...);
    await delay(...);
  }
}

main().catch(err => console.error(err));
```
so there's no potential for unhandled rejections.

**Comment by josephg** [comment]
Thanks for the report. That does indeed sound like a bug in node-foundationdb; and that flow is not something I've exercised a lot. I'll see if I can reproduce it.

**Comment by aikoven** [comment]
Apparently it was a bug in my code.
