### ISSUE TITLE
Last byte of string value is replaced by zero byte

### ISSUE THREAD

**Issue by aikoven** [josephg/node-foundationdb#40]
This started happening after updating to `0.10.4`. I narrowed it down to a set of commands in Node REPL:

```
> const  fdb = require('foundationdb')
> fdb.setAPIVersion(600)
undefined
> db = fdb.openSync()
> db.set('key', '123')
Promise { <pending> }
> db.get('key').then(console.log)
Promise { <pending> }
> <Buffer 31 32 00>
```

It can be seen that the last byte became `00`.

This doesn't happen if I pass `Buffer.from('123')` to the `set()` call.

**Comment by josephg** [comment]
Yikes thats really bad, and supports what I was saying [here](https://github.com/josephg/node-foundationdb/pull/39#issuecomment-606951940) that we need to either remove the second code path (using strings) or add much more testing for it. Thanks for the report - I'll fix & publish an updated version now.

**Comment by josephg** [comment]
... The silver lining is that that test code would have crashed in 0.10.3 due to the `Assertion failed: (owned == false)` issue. Hopefully not many people are doing that in production.

**Comment by josephg** [comment]
📦 foundationdb@0.10.6

**Comment by aikoven** [comment]
Yep, we updated to `0.10.4` because we started to experience these crashes. Haven't pushed it to production.

Thanks for the quick response!
