### ISSUE TITLE
Callback API seems to be broken

### ISSUE THREAD

**Issue by ex3ndr** [josephg/node-foundationdb#45]
I am trying to use callback api instead of promise one and they all are never called.

**Comment by josephg** [comment]
The callback api is supported by the native module but the node library which wraps it only supports promises. Why do you want to use callbacks? Like, what problem do you have that that solves?

**Comment by ex3ndr** [comment]
Well, they are still exists in typings everywhere. I was thinking to benchmark and improve performance and wanted to rule out promises and it seems that they are not working at all.

**Comment by josephg** [comment]
Oh rad - I'd be very curious to see the results of that benchmark.

The typings should be correct. Taking a look at the code, `tn.get()` and a few other transaction methods should support callbacks. Hm, my test program with it is failing though. I'm taking a look...

**Comment by josephg** [comment]
Oh yeah this is mega broken. [This call to call_function](https://github.com/josephg/node-foundationdb/blob/486e238aeb316f1d2ecc1c8256943e1268f72824/src/future.cpp#L187) is returning `napi_invalid_arg` and we're just throwing away the error. As a result, the callback is indeed never called. I'll fix it up when I have some time later today.

**Comment by josephg** [comment]
Ok if you checkout master it should be working now - although the API is pretty awkward to use with callbacks because there's no helper wrapper to do the standard transaction retry loop logic. Let me know how you get on with it!
