### ISSUE TITLE
Support for M1

### ISSUE THREAD

**Issue by shivanan** [josephg/node-foundationdb#50]
On a M1 Mac - when I try to install I get the following:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for foundationdb@1.0.2: wanted {"os":"any","arch":"x64"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    any
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64
```

Is there a way to make it work on this new architecture?

**Comment by josephg** [comment]
Oh good catch. I have no idea - I don't have an M1 mac to test and experiment with. I would happy fix this bug in exchange for an M1 mac. Otherwise someone else will need to pick it up!

**Comment by josephg** [comment]
Made a request for help on the [fdb forums](https://forums.foundationdb.org/t/help-needed-m1-support-for-the-nodejs-bindings/2535)

**Comment by shivanan** [comment]
Thanks. Will do. I feel like we just need to set some npm package settings so that it uses the x64 version on Darwin-arm64

**Comment by josephg** [comment]
The specific error you're running into comes from [this in package.json](https://github.com/josephg/node-foundationdb/blob/e36c0efe70c564ed7cd5eea4e0f3cf314fa15d7e/package.json#L16-L18):

```
  "cpu": [
    "x64"
  ],
```

If you remove that, does it build? There may be other changes required in [binding.gyp](https://github.com/josephg/node-foundationdb/blob/master/binding.gyp).

**Comment by josephg** [comment]
There is probably also a way to cross-compile the package for ARM from an intel mac, but I'm not sure how to do this.

**Comment by josephg** [comment]
Ok - I managed to build a universal binary for macos and it seems to work. But foundationdb itself doesn't yet support the apple M1. With 6.2.28 (latest at time of writing):

```
$ lipo -archs /usr/local/lib/libfdb_c.dylib 
x86_64
```

There's an [open PR for apple silicon support on foundationdb](https://github.com/apple/foundationdb/pull/4110) but it hasn't yet been merged.

I've updated package.json to remove the x86_64 restriction and updated the github actions to generate prebuilds for arm64. But I have no idea what Rosetta's behaviour would be in this case - it should be able to use the x86 binaries for everything, but I couldn't speculate on what it actually does. I'm worried with prebuilds for arm nodejs will try to load the native arm version of the module, and that'll fail to run because it can't find a working ARM copy of libfdb_c.dylib.

**Comment by josephg** [comment]
Mmmf.. looks like github actions is still by default using an old version of macos which doesn't support building for ARM, and we can't [move to the newer images](https://github.com/actions/virtual-environments/issues/2486) until github adds capacity.

The current GH environment [does not support arm64](https://github.com/josephg/node-foundationdb/runs/1803597508?check_suite_focus=true#step:8:43).

**Comment by josephg** [comment]
Anyway, summary:

- [x] Remove x64 limitation in package.json
- [x] Get arm version of the module building (it builds fine already with no changes)
- [ ] ARM support in the native bindings code that we depend on (in libfdb_c). [Blocked by this PR](https://github.com/apple/foundationdb/pull/4110)
- [ ] Make ARM prebuilds for the foundationdb npm package. [Blocked by old macos images in gh-actions](https://github.com/actions/virtual-environments/issues/2486)
- [ ] Make this package work through Rosetta. (I can't test rosetta. Does it work already? Someone else will need to triage if it doesn't.)

**Comment by shivanan** [comment]
Hi
Sorry for the late reply. 
Yes I also tried to build in the same way and ran across similar issues.
Running under Rosetta should be fine - I doubt many people are running foundationdb on production on a mac.

Just that I get an error when trying to install the package. I will check your update and see if it works.

Thanks for the help!

**Comment by shivanan** [comment]
For the time being I've installed node  + npm under Rosetta so it all works fine for now. Thanks!

**Comment by aikoven** [comment]
Hey, we've managed to get a working setup with FoundationDB 6.3.23 for M1 in Docker. To do that, we had to enable knob `disable_posix_kernel_aio` for `fdbserver`, `fdbcli` and `node-foundationdb`:

```sh
fdbserver --knob_disable_posix_kernel_aio=1 <...other args>
```

```sh
fdbcli --exec 'configure new single ssd' --knob_disable_posix_kernel_aio=1
```

```ts
// do that before fdb.open()
fdb.configNetwork({    
  knob: 'disable_posix_kernel_aio=1',
});
```

**Comment by josephg** [comment]
I've just published foundationdb 2.0 with support via cross-compilation for ARM. Unfortunately, while I can compile the foundationdb library for arm directly on an arm computer (and the resulting artifact works fine), the module compiled on github actions doesn't seem to work. It gets this error:

```
> f.setAPIVersion(700)
dyld[90234]: missing symbol called
[1] 90234 abort node
```

I'd love some help figuring this out if anyone has time to debug it! `npm install foundationdb@2` will do it.

**Comment by atn34** [comment]
> ld: warning: ignoring file /usr/local/lib/libfdb_c.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

From `yarn prebuild --arch arm64` in https://github.com/josephg/node-foundationdb/actions/runs/4719016895/jobs/8369299925

I have an M1 machine, and if I try to `yarn prebuild --arch arm64` with the x86_64 libfdb_c I see the same thing you're seeing. But with the arm64 libfdb_c, it seems to work. Can we try installing the arm64 libfdb_c before `yarn prebuild --arch arm64` in github actions?

**Comment by josephg** [comment]
Sure.

Can x86 and ARM copies of foundationdb sit side-by-side? I guess we could just install x86 foundationdb, build for x86, uninstall, then install arm foundationdb and build for arm.

**Comment by josephg** [comment]
Yep, installing the arm version of foundationdb before building for arm did the trick. Thanks @atn34!

foundationdb@2.0.1 works with native apple silicon support now. Sorry this took so long to get sorted! Let me know if there's any problems.
