### ISSUE TITLE
API 630 Support

### ISSUE THREAD

**Issue by ex3ndr** [josephg/node-foundationdb#52]
Do you have any plans to upgrade API to 630 with transaction tagging support (https://github.com/apple/foundationdb/pull/2942) ?

**Comment by josephg** [comment]
Oh I missed that change. We can do that - interested in putting together a PR?

**Comment by ex3ndr** [comment]
I wish I could! But i will try to recruit someone from our team!

**Comment by ex3ndr** [comment]
Oof it seems it only needed to regenerate opts for this and no native coding required will do then!

**Comment by ex3ndr** [comment]
https://github.com/josephg/node-foundationdb/pull/53

**Comment by josephg** [comment]
Too easy :) thanks for the PR. I’ll publish a new version to npm later today.

**Comment by josephg** [comment]
📦️ foundationdb@1.1.0

**Comment by ex3ndr** [comment]
I forgot to bump maximum allowed version: https://github.com/josephg/node-foundationdb/pull/54

**Comment by josephg** [comment]
Cool. Merged and released as 1.1.1

**Comment by ex3ndr** [comment]
Yet another place :(
https://github.com/josephg/node-foundationdb/pull/55

**Comment by josephg** [comment]
Can you check that your PR actually fixes the issue before I merge it this time?

**Comment by ex3ndr** [comment]
Done!

1) Updated build script to use new fdb binaries (6.3.12) + fixed creation of data directory during build
2) Updated API version for tests to 630

Everything seems to work now.

**Comment by josephg** [comment]
... Sorry I've been dragging my heels on this. The installer for 6.3.12 is broken, which in turn means the CI can't run.

**Comment by hengsok** [comment]
Hi @josephg, when we try to set the API Version to 630, we got this error during run time.

FDBError: API version not valid
node_modules/foundationdb/dist/lib/apiVersion.js:37:30

Error happen at native_1.default.setAPIVersion(version);

This error happens with the latest fdb 6.3.15.

Thanks

**Comment by josephg** [comment]
Hi! I ran into issues deploying because the scripts are trying to build the library for windows, but windows support in foundationdb is being slowly deprecated - and the windows build is missing / broken.

I've just re-deployed foundationdb@1.1.2. Give that a crack @hengsok.

**Comment by hengsok** [comment]
@josephg thanks so much for the awesome work for this js lib. You really put in a lot of effort in it as I have looked through your majority of your code including the fdp-tuple. Just curious, where do you work at? Do you fork this library from the original author and continue to polish/improve it just for hobby? You seem to have very good understanding of both Javascript and fdb.  👍🏻

**Comment by josephg** [comment]
Aw thanks! I'm at the moment working on braid as part of [the invisible college](https://invisible.college/). Yeah I maintain this mostly as a hobby - though it honestly doesn't need much maintenance at this point. This code started as a fork, but I don't know if any of the original code remains. The native module was rewritten to support napi, and the native code was rewritten in typescript with promises rather than JS.

As for the range reads thing - yeah, well spotted. Looks like a typo.

**Comment by hengsok** [comment]
Nice good job! Great you are working on something interesting there. I think you did an excellent job at writing the documentation. It is pretty detailed although when I need additional features, I just dig through your lib directly. :) Such as setting RetryLimit, CausalReadRisky etc. :D It is good you had those options in there. There are many hidden gems in the code.

**Comment by josephg** [comment]
Yeah thanks. Those options are exposed by libfdb_c, which is the raw bindings library maintained by the foundationdb team. They're all exposed & documented through typescript type definitions at least.
