### ISSUE TITLE
Multi thread clients for connecting to different cluster

### ISSUE THREAD

**Issue by hengsok** [josephg/node-foundationdb#58]
Hi @josephg, 

On Apple FDB documentation, it mentioned about multi threaded client for connecting to different clusters, could you help explain how can we set this option up or what is the code for connecting to multiple FDB clusters?  Thanks!
https://apple.github.io/foundationdb/api-general.html#multi-threaded-client

**Comment by josephg** [comment]
Hi!

It should work the same as other client libraries. Just connect to mulitple clusters. As for the multi-threaded client option, [try it out](https://github.com/josephg/node-foundationdb/blob/c1165539e5d4aea4765d8f6f6444a684156a1a21/lib/opts.g.ts#L202-L207). Though I'm not sure how much difference you'll see in performance, or what the implications are. You'll need to:

1. Set the FDB version
2. Use `fdb.configNetwork({client_threads_per_version: xxx})`
3. Open multiple clusters by making multiple db objects (using multiple calls to `open(clusterFileName)`
