### ISSUE TITLE
`directory.open` fails with error "The given prefix is already in use"

### ISSUE THREAD

**Issue by aikoven** [josephg/node-foundationdb#63]
I'm getting sporadic errors that say "The given prefix is already in use" when I'm trying to open a directory using

```ts
fdb.directory.open(db, name);
```

As far as I can see from the code, we only get to [that branch](https://github.com/josephg/node-foundationdb/blob/v1.1.2/lib/directory.ts#L608) when the `prefix` is explicitly specified. So this is probably due to the fact that we write to the `prefix` variable that is out of the scope of the transaction body, so its value gets preserved through transaction retries.

I've checked the same function in [Python implementation](https://github.com/apple/foundationdb/blob/6.3.22/bindings/python/fdb/directory_impl.py#L232) and found that the `prefix` variable there lives inside the scope of the transaction.

**Comment by josephg** [comment]
Hmmm nice find. Can you make a test case that reproduces the issue? I’d like to make sure we fix the problem and that it doesn’t happen again.

**Comment by josephg** [comment]
Meanwhile I've published foundationdb@1.1.3, which should fix the issue. Give it a try and let me know.

The bug looks straightforward even though its a bit of a nightmare to test. Ideally I'd like to add a unit test for this fix too - but I'm feeling a bit lazy.

**Comment by aikoven** [comment]
Thanks for the fix.

I added a test case in #64 that failed 10 out of 10 times with 1.1.2. It passes with 1.1.3.

**Comment by josephg** [comment]
Awesome - nice one! Thanks for tracking this down and reporting.
