### ISSUE TITLE
Support for foundationdb v7.*

### ISSUE THREAD

**Issue by HaddadJoe** [josephg/node-foundationdb#71]
i'm trying to connect to a cluster of version 7.1.30 

```
let fdb = require('foundationdb');

> fdb.setAPIVersion(710);
Uncaught:
Error: Cannot use foundationdb protocol version 710 > 630. This version of node-foundationdb only supports protocol versions <= 630.

Please update node-foundationdb if you haven't done so then file a ticket:
https://github.com/josephg/node-foundationdb/issues

Until this is fixed, use FDB API version 630.

    at Object.set (/app/node_modules/foundationdb/dist/lib/apiVersion.js:28:19)
> 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
> 
```

Relying on version 630 the queries do not resolve and just hang.

**Comment by josephg** [comment]
Hi!

The foundationdb API version needs to be <= your database version, and <= the maximum supported API version in node-foundationdb. So you can just use API version 630 even though you're using foundationdb 7.1.30.

We can probably bump node-foundationdb to support API versions up to 710. I haven't been using this library myself, so it hasn't been getting a lot of attention.

Are there new features in API version 700 or 710 which you want to use?

**Comment by josephg** [comment]
Hi! I just updated the package to support foundationdb 7.2. Give it a try and let me know if it works for you - `npm install foundationdb@2`. Windows support had to be removed due to an [outstanding issue](https://forums.foundationdb.org/t/fdb-c-types-h-missing-in-windows-install-image/3817).
